### PR TITLE
Upgrade default prometheus version from 2.15.2 to 2.23.0

### PR DESCRIPTION
**Pull request by waiariki-koia**

### CODE REVIEW

**Comment by surajnarwade** [comment]
are we going to upgrade Thanos in different PR?

**Comment by waiariki-koia** [comment]
Yeah I was going to do them in separate PRs to avoid combining changes. But I can put it in here if thats better?

**Review by rhysemmas — APPROVED** [review]

**Comment by rhysemmas** [comment]
Sorry just saw the comments - upgrading Thanos in a separate PR would be safer, we should try to only change 1 thing at a time

**Comment by surajnarwade** [comment]
sounds good to me

**Pull request merged**
